cp ../gsmhn/center/src/main/Java/com/kld/gsm/center/dao/oss_daily_SelfOilMapper.java center/src/main/Java/com/kld/gsm/center/dao/
cp ../gsmhn/center/src/main/Java/com/kld/gsm/center/dao/oss_daily_TradeInventoryMapper.java center/src/main/Java/com/kld/gsm/center/dao/
cp ../gsmhn/center/src/main/Java/com/kld/gsm/center/domain/oss_daily_SelfOil.java center/src/main/Java/com/kld/gsm/center/domain/
cp ../gsmhn/center/src/main/Java/com/kld/gsm/center/domain/oss_daily_TradeInventory.java center/src/main/Java/com/kld/gsm/center/domain/
cp ../gsmhn/center/src/main/Java/com/kld/gsm/center/service/DTradeInventoryService.java center/src/main/Java/com/kld/gsm/center/service/
cp ../gsmhn/center/src/main/Java/com/kld/gsm/center/service/DselfOilService.java center/src/main/Java/com/kld/gsm/center/service/
cp ../gsmhn/center/src/main/Java/com/kld/gsm/center/service/impl/DTradeInventoryServiceImpl.java center/src/main/Java/com/kld/gsm/center/service/impl/
cp ../gsmhn/center/src/main/Java/com/kld/gsm/center/service/impl/DselfOilServiceImpl.java center/src/main/Java/com/kld/gsm/center/service/impl/
cp ../gsmhn/center/src/main/Java/com/kld/gsm/center/util/action.java center/src/main/Java/com/kld/gsm/center/util/
cp ../gsmhn/center/src/main/Java/com/kld/gsm/center/util/getSelfOilUntil.java center/src/main/Java/com/kld/gsm/center/util/
cp ../gsmhn/center/src/main/Java/com/kld/gsm/center/web/controller/AddRCYYController.java center/src/main/Java/com/kld/gsm/center/web/controller/
cp ../gsmhn/center/src/main/Java/com/kld/gsm/center/web/controller/TIController.java center/src/main/Java/com/kld/gsm/center/web/controller/
cp ../gsmhn/center/src/main/Java/com/kld/gsm/center/web/webcontroller/WebHomeControllerWeb.java center/src/main/Java/com/kld/gsm/center/web/webcontroller/
cp ../gsmhn/center/src/main/Java/com/kld/gsm/center/web/webcontroller/WebSysmanageController.java center/src/main/Java/com/kld/gsm/center/web/webcontroller/
cp ../gsmhn/center/src/main/Java/com/kld/gsm/center/web/webcontroller/basicdata/GasStationController.java center/src/main/Java/com/kld/gsm/center/web/webcontroller/basicdata/
cp ../gsmhn/center/src/main/resources/conf/hnservices.properties center/src/main/resources/conf/
cp ../gsmhn/center/src/main/resources/sqlmap/oss_daily_SelfOilMapper.xml center/src/main/resources/sqlmap/
cp ../gsmhn/center/src/main/resources/sqlmap/oss_daily_TradeInventoryMapper.xml center/src/main/resources/sqlmap/
cp ../gsmhn/center/src/main/webapp/WEB-INF/basicdata/selfOilpage.vm center/src/main/webapp/WEB-INF/basicdata/
cp ../gsmhn/center/src/main/webapp/WEB-INF/common/left.vm center/src/main/webapp/WEB-INF/common/
cp ../gsmhn/center/src/main/webapp/WEB-INF/common/top.vm center/src/main/webapp/WEB-INF/common/
cp ../gsmhn/core/src/main/java/com/kld/gsm/ATG/dao/DailyTradeInventoryDao.java core/src/main/java/com/kld/gsm/ATG/dao/
cp ../gsmhn/core/src/main/java/com/kld/gsm/ATG/domain/DailyTradeInventory.java core/src/main/java/com/kld/gsm/ATG/domain/
cp ../gsmhn/core/src/main/resources/mysqlmap/DailyTradeInventoryMapper.xml core/src/main/resources/mysqlmap/
cp ../gsmhn/ctrl/src/main/java/com/kld/gsm/coord/servcie/impl/ShiftServiceImpl.java ctrl/src/main/java/com/kld/gsm/coord/servcie/impl/
cp ../gsmhn/ctrl/src/main/java/com/kld/gsm/coord/servcie/impl/TransacServiceImpl.java ctrl/src/main/java/com/kld/gsm/coord/servcie/impl/
cp ../gsmhn/syntocenter/src/main/java/com/kld/gsm/syntocenter/service/impl/synDailyRunningImpl.java syntocenter/src/main/java/com/kld/gsm/syntocenter/service/impl/
cp ../gsmhn/syntocenter/src/main/java/com/kld/gsm/syntocenter/service/synDailyRunning.java syntocenter/src/main/java/com/kld/gsm/syntocenter/service/
cp ../gsmhn/syntocenter/src/main/java/com/kld/gsm/syntocenter/timetask/DailyPolling.java syntocenter/src/main/java/com/kld/gsm/syntocenter/timetask/
cp ../gsmhn/syntocenter/src/main/java/com/kld/gsm/syntocenter/timetask/DailyPollingByWhile.java syntocenter/src/main/java/com/kld/gsm/syntocenter/timetask/
cp ../gsmhn/syntocenter/src/main/resource/config/services.properties syntocenter/src/main/resource/config/
