/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Systemv_IPCKey */

#ifndef _Included_Systemv_IPCKey
#define _Included_Systemv_IPCKey
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Systemv_IPCKey
 * Method:    getIntj
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Systemv_IPCKey_getIntj
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
