/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kld_gsm_ATGDevice_ATGDevice */

#ifndef _Included_com_kld_gsm_ATGDevice_ATGDevice
#define _Included_com_kld_gsm_ATGDevice_ATGDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kld_gsm_ATGDevice_ATGDevice
 * Method:    init
 * Signature: (Lcom/kld/gsm/ATGDevice/atg_init_in_t;)I
 */
JNIEXPORT jint JNICALL Java_com_kld_gsm_ATGDevice_ATGDevice_init
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_kld_gsm_ATGDevice_ATGDevice
 * Method:    setCorrection
 * Signature: (Ljava/util/List;)I
 */
JNIEXPORT jint JNICALL Java_com_kld_gsm_ATGDevice_ATGDevice_setCorrection
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_kld_gsm_ATGDevice_ATGDevice
 * Method:    setProbe
 * Signature: (Ljava/util/List;)I
 */
JNIEXPORT jint JNICALL Java_com_kld_gsm_ATGDevice_ATGDevice_setProbe
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_kld_gsm_ATGDevice_ATGDevice
 * Method:    getStock
 * Signature: (Ljava/util/List;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_kld_gsm_ATGDevice_ATGDevice_getStock
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_kld_gsm_ATGDevice_ATGDevice
 * Method:    getTimeStock
 * Signature: (Ljava/util/List;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_kld_gsm_ATGDevice_ATGDevice_getTimeStock
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_kld_gsm_ATGDevice_ATGDevice
 * Method:    getOilIn
 * Signature: (Ljava/util/List;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_kld_gsm_ATGDevice_ATGDevice_getOilIn
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_kld_gsm_ATGDevice_ATGDevice
 * Method:    getAlarm
 * Signature: (Ljava/util/List;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_kld_gsm_ATGDevice_ATGDevice_getAlarm
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_kld_gsm_ATGDevice_ATGDevice
 * Method:    getFailure
 * Signature: (Ljava/util/List;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_kld_gsm_ATGDevice_ATGDevice_getFailure
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_kld_gsm_ATGDevice_ATGDevice
 * Method:    checkTime
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_kld_gsm_ATGDevice_ATGDevice_checkTime
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_kld_gsm_ATGDevice_ATGDevice
 * Method:    alarmSetter
 * Signature: (Ljava/util/List;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_kld_gsm_ATGDevice_ATGDevice_alarmSetter
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_kld_gsm_ATGDevice_ATGDevice
 * Method:    chgOilInfo
 * Signature: (Ljava/util/List;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_kld_gsm_ATGDevice_ATGDevice_chgOilInfo
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_kld_gsm_ATGDevice_ATGDevice
 * Method:    getCapacityTable
 * Signature: (Ljava/util/List;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_kld_gsm_ATGDevice_ATGDevice_getCapacityTable
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_kld_gsm_ATGDevice_ATGDevice
 * Method:    setCapacityTable
 * Signature: (Lcom/kld/gsm/ATGDevice/atg_capacity_data_in_t;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_kld_gsm_ATGDevice_ATGDevice_setCapacityTable
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_kld_gsm_ATGDevice_ATGDevice
 * Method:    startLiquid
 * Signature: (Ljava/util/List;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_kld_gsm_ATGDevice_ATGDevice_startLiquid
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_kld_gsm_ATGDevice_ATGDevice
 * Method:    stopLiquid
 * Signature: (Ljava/util/List;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_kld_gsm_ATGDevice_ATGDevice_stopLiquid
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_kld_gsm_ATGDevice_ATGDevice
 * Method:    liquidReport
 * Signature: (Ljava/util/List;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_kld_gsm_ATGDevice_ATGDevice_liquidReport
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_kld_gsm_ATGDevice_ATGDevice
 * Method:    getDeviceInfo
 * Signature: (Ljava/util/List;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_kld_gsm_ATGDevice_ATGDevice_getDeviceInfo
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_kld_gsm_ATGDevice_ATGDevice
 * Method:    HightOLiter
 * Signature: (Ljava/util/List;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_kld_gsm_ATGDevice_ATGDevice_HightOLiter
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_kld_gsm_ATGDevice_ATGDevice
 * Method:    getPowerRecord
 * Signature: (Ljava/util/List;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_kld_gsm_ATGDevice_ATGDevice_getPowerRecord
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_kld_gsm_ATGDevice_ATGDevice
 * Method:    clear
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_kld_gsm_ATGDevice_ATGDevice_clear
  (JNIEnv *, jclass);

/*
 * Class:     com_kld_gsm_ATGDevice_ATGDevice
 * Method:    atg_param
 * Signature: (Ljava/lang/String;Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_kld_gsm_ATGDevice_ATGDevice_atg_1param
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_kld_gsm_ATGDevice_ATGDevice
 * Method:    atg_init
 * Signature: (Lcom/kld/gsm/ATGDevice/atg_init_in_t;)I
 */
JNIEXPORT jint JNICALL Java_com_kld_gsm_ATGDevice_ATGDevice_atg_1init
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_kld_gsm_ATGDevice_ATGDevice
 * Method:    testList
 * Signature: (Ljava/util/ArrayList;)I
 */
JNIEXPORT jint JNICALL Java_com_kld_gsm_ATGDevice_ATGDevice_testList
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_kld_gsm_ATGDevice_ATGDevice
 * Method:    getfromc
 * Signature: (I)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_kld_gsm_ATGDevice_ATGDevice_getfromc
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
